GET http://localhost:3000/states

GET http://localhost:3000/districts/7

GET http://localhost:3000/states/3

DELETE http://localhost:3000/states/5

POST http://localhost:3000/districts/
Content-type: application/json

{
    "districtName":"Kozhikode",
    "stateId":5,
    "cases":89,
    "cured":50,
    "active":30,
    "deaths":10

}